spring:
  application:
    name: payments
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Cấu hình tối ưu cho Connection Pool
      minimum-idle: 5         # Số kết nối tối thiểu luôn tồn tại trong pool
      maximum-pool-size: 20   # Số kết nối tối đa trong pool
      idle-timeout: 300000    # Thời gian tối đa (ms) cho các kết nối không hoạt động trước khi đóng (5 phút)
      max-lifetime: 1800000   # Thời gian tối đa (ms) sống của kết nối (30 phút)
      connection-timeout: 30000 # Thời gian tối đa (ms) để nhận được kết nối từ pool (30 giây)
      validation-timeout: 5000 # Thời gian tối đa (ms) để kiểm tra tính hợp lệ của kết nối (5 giây)
      leak-detection-threshold: 15000 # Thời gian (ms) để phát hiện rò rỉ kết nối (15 giây)
      connection-test-query: SELECT 1 # Câu truy vấn để kiểm tra tính hợp lệ của kết nối
  cloud:
    stream:
      bindings:
        sendPayment-out-0:
          destination: send-update-status
        sendRefund-out-0:
          destination: send-refund-status
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    connection-timeout: 5s
    port: ${RABBITMQ_PORT}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL}
    register-with-eureka: true
    fetch-registry: true

payment:
  vnpay:
    vnp_PayUrl: ${PAYMENT_VNPAY_VNP_PAYURL}
    vnp_TmnCode: ${PAYMENT_VNPAY_VNP_TMNCODE}
    secretKey: ${PAYMENT_VNPAY_SECRETKEY}
    vnp_ReturnUrl: ${PAYMENT_VNPAY_VNP_RETURNURL}
    vnp_Version: ${PAYMENT_VNPAY_VNP_VERSION}
    vnp_Command: ${PAYMENT_VNPAY_VNP_COMMAND}
    orderType: ${PAYMENT_VNPAY_ORDERTYPE}
refund:
  vnpay:
    vnp_RefundUrl: ${REFUND_VNPAY_VNP_REFUNDURL}
    vnp_Version: ${REFUND_VNPAY_VNP_VERSION}
    vnp_Command: ${REFUND_VNPAY_VNP_COMMAND}
    vnp_TmnCode: ${REFUND_VNPAY_VNP_TMNCODE}
    secretKey: ${REFUND_VNPAY_SECRETKEY}

server:
  port: 8083

logging:
  level:
    com.thuc.payments: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true