spring:
  application:
    name: payments
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-hotel
    username: postgres
    password: Anhthucdz1234!
    driver-class-name: org.postgresql.Driver
    hikari:
      # Cấu hình tối ưu cho Connection Pool
      minimum-idle: 5         # Số kết nối tối thiểu luôn tồn tại trong pool
      maximum-pool-size: 20   # Số kết nối tối đa trong pool
      idle-timeout: 300000    # Thời gian tối đa (ms) cho các kết nối không hoạt động trước khi đóng (5 phút)
      max-lifetime: 1800000   # Thời gian tối đa (ms) sống của kết nối (30 phút)
      connection-timeout: 30000 # Thời gian tối đa (ms) để nhận được kết nối từ pool (30 giây)
      validation-timeout: 5000 # Thời gian tối đa (ms) để kiểm tra tính hợp lệ của kết nối (5 giây)
      leak-detection-threshold: 15000 # Thời gian (ms) để phát hiện rò rỉ kết nối (15 giây)
      connection-test-query: SELECT 1 # Câu truy vấn để kiểm tra tính hợp lệ của kết nối
  cloud:
    stream:
      bindings:
        sendPayment-out-0:
          destination: send-update-status
        sendRefund-out-0:
          destination: send-refund-status
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    connection-timeout: 5s
    port: 5672
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: true
    fetch-registry: true

payment:
  vnpay:
    vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    vnp_TmnCode: 58X4B4HP
    secretKey: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    vnp_ReturnUrl: http://localhost:8072/bookinghotel/payments/api/payments/vn-pay-callback
    vnp_Version: 2.1.0
    vnp_Command: pay
    orderType: other
refund:
  vnpay:
    vnp_RefundUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    vnp_Version: 2.1.0
    vnp_Command: refund
    vnp_TmnCode: 58X4B4HP
    secretKey: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ

server:
  port: 8083

logging:
  level:
    com.thuc.payments: debug