spring:
  application:
    name: messages
  cloud:
    function:
      definition: sendEmailCreateAccount; sendEmailConfirmBill ; sendEmailRefundBill
    stream:
      bindings:
        sendEmailCreateAccount-in-0:
          destination: send-communication
          group: ${spring.application.name}
          consumer:
            max-attempts: 3 #
            back-off-initial-interval: 2000 # đợi 2s retry lần đaầu
            back-off-multiplier: 2.0 # x2 khi retry
            default-retryable: true # retry tất cả lỗi
            retryable-exceptions:
              java.lang.RuntimeException: true
        sendEmailCreateAccount-out-0:
          destination: communication-sent
        sendEmailConfirmBill-in-0:
          destination: send-confirm-bill
          group: ${spring.application.name}
          consumer:
            max-attempts: 3 #
            back-off-initial-interval: 2000 # đợi 2s retry lần đaầu
            back-off-multiplier: 2.0 # x2 khi retry
            default-retryable: true # retry tất cả lỗi
            retryable-exceptions:
              java.lang.RuntimeException: true
        sendEmailRefundBill-in-0:
          destination: send-refund-bill
          group: ${spring.application.name}
          consumer:
            max-attempts: 3 #
            back-off-initial-interval: 2000 # đợi 2s retry lần đaầu
            back-off-multiplier: 2.0 # x2 khi retry
            default-retryable: true # retry tất cả lỗi
            retryable-exceptions:
              java.lang.RuntimeException: true
        sendEmailConfirmBill-out-0:
          destination: confirm-bill-send
        sendEmailRefundBill-out-0:
          destination: refund-bill-send

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      smtp:
        auth: true
      mail:
        smtp:
          starttls:
            enable: true

  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8084

logging:
  level:
    com.thuc.messages: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true