spring:
  application:
    name: bookingservice
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-hotel
    username: postgres
    password: Anhthucdz1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com.thuc.BookingService: debug