spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false # Tự động cấu hình các route gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # download public certificates de resourceserver ket noi authserver validate token
          jwk-set-uri: ${SECURITY_OAUTH2_RESOURCESERVER_JWT_SET_URI}
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
URL_FRONTEND: ${URL_FRONTEND}
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL}
server:
  port: 8072
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
