spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false # Tự động cấu hình các route gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # download public certificates de resourceserver ket noi authserver validate token
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 8072
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
