spring:
  application:
    name: bookings
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-hotel
    username: postgres
    password: Anhthucdz1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      connect-timeout: 2s
      timeout: 5s
  cloud:
    function:
      definition: sendPayment; sendRefund
    stream:
      bindings:
        sendPayment-in-0:
          destination: send-update-status
          group: ${spring.application.name}
        sendRefund-in-0:
          destination: send-refund-status
          group: ${spring.application.name}
        sendRefund-out-0:
          destination: send-refund-bill
        sendPayment-out-0:
          destination: send-confirm-bill



server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    com.thuc.bookings: debug