spring:
  application:
    name:   users
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-hotel
    username: postgres
    password: Anhthucdz1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8071
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com.thuc.users: debug

keycloak-credential:
  auth-server-url: http://localhost:7080
  client-id: create-account-keycloak
  client-secret: fdD5N5XzbJiLsN3lrL8SiEB5kqCNJ20H
  grant-type: client_credentials
  realm: master

keycloak-authorization:
  token-endpoint: http://localhost:7080/realms/master/protocol/openid-connect/token
  client-id: booking-hotel
  client-secret: iwHgKCzbMy9ZO6Qo8sicpSTC3kgGXFRP
  grant-type: authorization_code
  realm: master
  redirect-uri: http://localhost:3000/callback