
spring:
  application:
    name: rooms
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Cấu hình tối ưu cho Connection Pool
      minimum-idle: 5         # Số kết nối tối thiểu luôn tồn tại trong pool
      maximum-pool-size: 20   # Số kết nối tối đa trong pool
      idle-timeout: 300000    # Thời gian tối đa (ms) cho các kết nối không hoạt động trước khi đóng (5 phút)
      max-lifetime: 1800000   # Thời gian tối đa (ms) sống của kết nối (30 phút)
      connection-timeout: 30000 # Thời gian tối đa (ms) để nhận được kết nối từ pool (30 giây)
      validation-timeout: 5000 # Thời gian tối đa (ms) để kiểm tra tính hợp lệ của kết nối (5 giây)
      leak-detection-threshold: 15000 # Thời gian (ms) để phát hiện rò rỉ kết nối (15 giây)
      connection-test-query: SELECT 1 # Câu truy vấn để kiểm tra tính hợp lệ của kết nối
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: 2s
      timeout: 4s
  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: 5s
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL}
logging:
  level:
    com.thuc.rooms: DEBUG

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true